language: python
os: linux
dist: bionic
addons:
  apt:
    packages:
      - libboost-dev libboost-system-dev
      - qtbase5-dev libqt5svg5-dev
  coverity_scan:
    project:
      name: "rmartin16/qbittorrent-api"
      description: "Python client implementation for qBittorrent's Web API"
    notification_email: rmartin16@gmail.com
    build_command: "--no-command --fs-capture-search ./qbittorrentapi/"
    branch_pattern: coverity_scan
python:
  - 2.7
  #- 3.4  # not supported on bionic
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9-dev
  - 3.10-dev
  - pypy3
jobs:
  allow_failures:
    - python: pypy3
    - python: 3.9-dev
    - python: 3.10-dev
env:
  - QBT_VER="4.1.0"
  - QBT_VER="4.1.1"
  #- QBT_VER="4.1.2"  # nox version wouldn't start out of the box: fixed in https://github.com/qbittorrent/qBittorrent/pull/9365
  - QBT_VER="4.1.3"
  - QBT_VER="4.1.4"
  - QBT_VER="4.1.5"
  - QBT_VER="4.1.6"
  - QBT_VER="4.1.7"
  - QBT_VER="4.1.8"
  - QBT_VER="4.1.9"
  - QBT_VER="4.1.9.1"
  - QBT_VER="4.2.0"
  - QBT_VER="4.2.1"
  - QBT_VER="4.2.2"
  - QBT_VER="4.2.3"
  - QBT_VER="4.2.4"
  - QBT_VER="4.2.5"
cache:
  directories:
    - $HOME/deb  # until deb downloads are more reliable...
    - $HOME/.cache/pip
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install codecov
  # coverity
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca
  # prepare to install qbittorrent things
  - mkdir -p $HOME/deb
  - mkdir -p $HOME/Downloads  # default torrent download location
  - alias wget="wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 100"
  # install libtorrent-rasterbar
  - if [ ! -f $HOME/deb/libtorrent-rasterbar9_amd64.deb ]; then wget https://bit.ly/libtorrent-rasterbar9-1-1-1 -O $HOME/deb/libtorrent-rasterbar9_amd64.deb; fi
  - if [ ! -f $HOME/deb/libtorrent-rasterbar-dev_amd64.deb ]; then wget https://bit.ly/libtorrent-rasterbar-dev-1-1-1 -O $HOME/deb/libtorrent-rasterbar-dev_amd64.deb; fi
  - sudo dpkg -i $HOME/deb/libtorrent-rasterbar-dev_amd64.deb $HOME/deb/libtorrent-rasterbar9_amd64.deb
  # install qBittorrent
  - if [ ! -f $HOME/deb/qbittorrent_nox_amd64.deb ]; then wget https://bit.ly/qbittorrent-nox-amd64-$(echo "$QBT_VER" | tr . -) -O $HOME/deb/qbittorrent_nox_amd64.deb; fi
  - sudo dpkg -i $HOME/deb/qbittorrent_nox_amd64.deb
  # start qBittorrent
  - $QBT_PATH/bin/qbittorrent-nox --daemon
install:
  - pip install .
script: if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then pytest; fi
after_success:
  - codecov
